spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/gassys_userdb
    username: gassys_userdb_user
    password: gassys_userdb_user
#    url: jdbc:h2:mem:.
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password



  jpa:
    hibernate:
      ddl-auto:
        create

server:
  port: 8081